//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sualiado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kardex
    {
        public int Consecut { get; set; }
        public int Cod_Pers_Fk { get; set; }
        public int Cod_Mov_Fk { get; set; }
        public int Cod_Produc_Fk { get; set; }
        public Nullable<int> Dcto { get; set; }
        public int Cantidad { get; set; }
        public int Costo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Detalle { get; set; }
    
        public virtual movimientos movimientos { get; set; }
        public virtual persona persona { get; set; }
        public virtual producto producto { get; set; }
    }
}
