//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sualiado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.kardex = new HashSet<kardex>();
        }
    
        public int Cod_Produc { get; set; }
        public string Nombre_Produc { get; set; }
        public Nullable<int> Existencias { get; set; }
        public string Precio_Venta { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> Cod_SubCategoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kardex> kardex { get; set; }
        public virtual subcategoria subcategoria { get; set; }

        public string Mensaje { get; set; }
    }
}
