//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sualiado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        public int Cod_Prove { get; set; }
        public int Cod_Pers_Fk { get; set; }
        public string Locacion { get; set; }
        public string Enlace { get; set; }
        public bool Activo { get; set; }
    
        public virtual persona persona { get; set; }
    }
}
